### ISSUE TITLE
Feat: 회원가입 기능 구현 (판매회원)

### ISSUE THREAD

**Issue by jsunbin** [jsunbin/hodu#56]
## Description
**회원가입 페이지**

- 회원가입 할 때는 모든 입력을 완료하고 동의하기 체크를 눌러야만 회원가입이 가능합니다.
- 회원 정보 입력 후 회원가입 버튼을 누르면 로그인 페이지로 이동합니다.
- 아이디의 중복 확인 버튼을 눌렀을 때 중복이 된다면 입력창 아래에 경고 문구가 나타납니다.
- ~~구매회원~~
  - ~~구매 회원 가입 탭을 누르고, 모든 입력을 마친 뒤(이용약관 체크박스 포함) 가입하기 버튼을 누르면 구매자로 회원가입이 됩니다.~~
- 판매회원
  - 판매회원 가입 탭을 누르고, 모든 입력을 마친 뒤(이용약관 체크박스 포함) 가입하기 버튼을 누르면 판매자로 회원가입이 됩니다.
  - 사업자 등록번호에서 인증 버튼을 눌렀을 때 10개의 숫자가 아니면 입력 창 아래에 경고메세지가 나타납니다

## To-do
- [x] API를 연결하여 판매회원 회원가입 기능 구현
  - [x] 모든 필드는 필수로 작성해야 합니다.
  - [x] 비밀번호는 8자 이상, 영소문자를 포함해야 합니다.
  - [x]  핸드폰 번호는 010으로 시작하는 10~11자리 숫자로만 이루어져 있습니다.
  - [x] 판매회원 가입 탭을 누르고, 모든 입력을 마친 뒤(이용약관 체크박스 포함) 가입하기 버튼을 누르면 판매자로 회원가입이 됩니다.
  - [ ] 사업자 등록번호에서 인증 버튼을 눌렀을 때 10개의 숫자가 아니면 입력 창 아래에 경고메세지가 나타납니다.
