### ISSUE TITLE
Feat: 메인 페이지 기능 구현

### ISSUE THREAD

**Issue by jsunbin** [jsunbin/hodu#63]
## Description
메인 페이지 기능 구현

## To-do
- [x] API 연동하여 상품 목록 데이터 뿌리기
- [x] 목록에서 상품을 클릭하면 상품 상세 페이지로 이동
- [x] 상품에는 상품 판매자, 상품명, 가격이 보여짐
